### PR TITLE
DEV-13456 removed striim.conf and creating startUp.properties file

### PR DESCRIPTION
**Pull request by deepakstriim**
manually tested for Azure Sql and Azure Storage apps.
Had to change the pom version in build.properties to match the version of sample apps.

### CODE REVIEW

**Review by manish-striim — APPROVED** [review]

**Comment by rajeshnair** [comment]
@deepakstriim 

startUp.properties are missing at least 2 properties to be set from previous striim.conf

1.  TCP-IP clustering needs to be set to true
2. Both of the following properties need to be set to WA_NODE_PUBLIC_IP. Currently, only latter is being set    
     com.webaction.config.servernode.address
     com.webaction.config.node.public.address

**Comment by manish-striim** [comment]
Rajesh, what is the impact of server node. Address not being set? I guess agents won't be able to connect right?

**Comment by manish-striim** [comment]
Rajesh, can you add few user scenarios that once should test when testing solution templates? I believe able to login to the machine and striim UI and agent being able to connect to striim server and run an app that does on prem to cloud. Anything else that comes to mind?

**Comment by manish-striim** [comment]
Rajesh, with azure solution templates, do we automatically form cluster of more than 1 node is launched together?

**Comment by deepakstriim** [comment]
@rajeshnair I don' see TCP-IP clustering property explicitly set in striim.conf before my changes.

**Review by manish-striim — APPROVED** [review]

**Pull request merged**
